### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by marianbasti** [marianobasti/BarPOS#2]
- [ ]  Editar meses (uf)
- [ ]  Editar carta
- [x]  Set cantidad de comensales por mesa
- [ ] Interfaz cocina
- [ ] Generar tiquet fiscal
- [x] Controles de mesa (limpiar ordenes, reservas, Set metodo pago, mozo, cuotas por mesa

- [ ] Interfaz Visualizar data (lotta shit)

**Comment by marianbasti** [comment]
- [x] Seleccionar mozo que usa la interfaz
- [ ] Editar carta, precios, mozos
- [x] Contraseña

**Comment by marianbasti** [comment]
- [x] Ver reservas, cancelarlas automaticamente cuando pasan 15 minutos despues de la hora
- [x]  No permitir que se pisen las reservas
- [ ]  Poder cambiar el margen de tiempo para que las reservas no se pisen

**Comment by marianbasti** [comment]
- [ ] Cambiar contraseña del mozo
